################################################################################
# Copyright (c) 2024, NVIDIA CORPORATION. All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.
#
################################################################################

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape metrics from the via-server
  - job_name: "via-server"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["via-engine-local-merylm:36011"]

  # Scrape metrics from OpenTelemetry Collector
  - job_name: "otel-collector"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["otel-collector:8889"]

  # Scrape metrics from Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] 
